### ISSUE TITLE
Question regarding images used 

### ISSUE THREAD

**Issue by DanaIliescu** [mbpictures/react-product-configurator#2]
Dear Marius

I am interested in using your package for a React application I'm building and I was wondering what technique / program you used for exporting the images (belt, case, handle) and for colouring them. Otherwise, amazing package, thank you!!

**Comment by mbpictures** [comment]
Hi!

First of all thanks for your interest! For the demo, I used a single image of a backpack, split the different parts (belt, case, handle, ...) and colorized them using photoshop. There are many tutorials on how to cut out objects using photoshop. To colorize you can simply add a color/saturation adjustment layer and tick the "colorize" checkbox. This depends on what exactly you are going to do, as in some cases it would be better to photograph different product variations.
I hope this answers your question.
Best wishes
Marius

**Comment by DanaIliescu** [comment]
Yes, it does! Thank you so much and best wishes to you too! :)
