### ISSUE TITLE
Trigger event on Item change

### ISSUE THREAD

**Issue by jures** [mbpictures/react-product-configurator#3]
Hi,

You made a great configurator!!!
I just have 1 question, i'm trying to add an animation to each image with framer motion, so that when the selection changes the image would get re-animated.
Is there currently any callbacks that I can use?

Thank you!

**Comment by mbpictures** [comment]
Hi,

Thanks for your interest! Currently there's no event available which gets fired after changing the item selection. I will make an update in a few days, stay tuned!

**Comment by mbpictures** [comment]
Good news! 27fcdde231e9be44c655bc9ba600946afeef9ed0 adds a event called after the user changes his item selection. Version 2.0.1 adds this feature, simply update your package.json to use version 2.0.1.
